service: python-example-iam

provider:
  name: aws
  runtime: python3.8
  region: sa-east-1
  memorySize: 128
  iamRoleStatements:
    - Effect: "Allow"
      Action: 
        - "lambda:*"
      Resource:
        - "*"

functions:
  hello:
    handler: handler.hello